on:
  pull_request:
  push:

jobs:
  continue-on-error: true
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        nimversion:
          - binary:stable
          - binary:1.6.18
        os:
          - ubuntu-latest
          - macOS-13
          - windows-latest
        nimbleversion:
          - 0.13.1
          - 0.15.2
          - 0.16.2
    steps:
    - uses: actions/checkout@v1
    - uses: iffy/install-nim@v5
      with:
        version: ${{ matrix.nimversion }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upgrade nimble
      run: |
        nimble install -y nimble@${{ matrix.nimbleversion }}
    - name: Versions
      run: |
        nim -V
        nimble --version
    - name: Test
      run: |
        nimble install -y
        nim r tests/test1.nim
    